name: Automating image push to AWS ECR with oidc

on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_ACCOUNT_ID: 111810594106

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:  
          role-to-assume: arn:aws:iam::111810594106:role/ecs-push
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-2 \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build Docker image
        run: |
          registry="$AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/image_umami"
          sha=$(git rev-parse --short HEAD)
          primary_tag="${registry}:${sha}"

          echo "primary_tag=$primary_tag" >> $GITHUB_ENV

          docker build -f umami/Dockerfile -t $primary_tag umami/

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.primary_tag }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push image
        run: |
          docker push $primary_tag

          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" = "main" ]; then
            registry="$AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/image_umami"
            retention_tag="${registry}:latest"
            docker tag $primary_tag $retention_tag
            docker push $retention_tag
          fi
